### ISSUE TITLE
OWL-compliant?

### ISSUE THREAD

**Issue by YasinEl** [HUPO-PSI/psi-ms-CV#359]
Hello,

could it be that http://aber-owl.net/media/ontologies/MS/194/ms.owl is not OWL-compliant or am I doing something wrong?

from owlready2 import get_ontology

onto = get_ontology('ms.owl').load()

gives

` TypeError: 'http://purl.obolibrary.org/obo/NCIT_C16847' belongs to more than one entity types (cannot be both a property and a class/an individual)!`

I did not have the same problem with http://aber-owl.net/media/ontologies/MS/188/ms.owl but did not try everything in between. 

Thank you

**Comment by mobiusklein** [comment]
I am still doing root cause analysis on this. It seems that our OBO to OWL conversion process previously treated `NCIT:C16847` as both an locally defined class and an externally defined property, but later began applying both types to the locally defined entity.

Other OWL-consuming tools do not seem to have an issue with this state. Is this something specific to `owlready2`?

**Comment by YasinEl** [comment]
I have only encountered this with owlready2 and have not tested others. Are you aware of others which are compatible with ms.owl?

**Comment by YasinEl** [comment]
Hello I just wanted to check if you had a chance to look at this? Thank you!

**Comment by mobiusklein** [comment]
I will get to this. I understand why it is important, which I did not before. I haven't been back to my home long enough in the last month to do much long term work since the workshop due to family medical exigency.

I will try to do this using a fresh tooling download but it probably won't match the set up I used when I set up the release automation.

**Comment by YasinEl** [comment]
Thank you a lot and take all the time you need!

**Comment by YasinEl** [comment]
Thank you!


Unfortunately now I get:

```
from owlready2 import get_ontology
import owlready2

# print version of owlready in use
print(owlready2.VERSION)  


onto = get_ontology('./data/ms.owl').load()
```

```
0.47
Traceback (most recent call last):
  File "owlready2_optimized.pyx", line 385, in owlready2_optimized.parse_rdfxml
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 24, column 75

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/yasin/miniconda3/lib/python3.12/site-packages/owlready2/driver.py", line 217, in do_parse
    if   format == "rdfxml": owlready2_optimized.parse_rdfxml(f, queue, default_base, batch_size)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "owlready2_optimized.pyx", line 387, in owlready2_optimized.parse_rdfxml
owlready2.base.OwlReadyOntologyParsingError: RDF/XML parsing error in file ./data/ms.owl, line 24, column 75.
Traceback (most recent call last):
  File "owlready2_optimized.pyx", line 385, in owlready2_optimized.parse_rdfxml
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 24, column 75

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/yasin/miniconda3/lib/python3.12/site-packages/owlready2/driver.py", line 217, in do_parse
    if   format == "rdfxml": owlready2_optimized.parse_rdfxml(f, queue, default_base, batch_size)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "owlready2_optimized.pyx", line 387, in owlready2_optimized.parse_rdfxml
owlready2.base.OwlReadyOntologyParsingError: RDF/XML parsing error in file ./data/ms.owl, line 24, column 75.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yasin/projects/playground/code/test_owl.py", line 8, in <module>
    onto = get_ontology('./data/ms.owl').load()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yasin/miniconda3/lib/python3.12/site-packages/owlready2/namespace.py", line 1008, in load
    try:     new_base_iri = self.graph.parse(fileobj, default_base = self._orig_base_iri, **args)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yasin/miniconda3/lib/python3.12/site-packages/owlready2/driver.py", line 267, in parse
    raise e
  File "/home/yasin/miniconda3/lib/python3.12/site-packages/owlready2/driver.py", line 263, in parse
    onto_base_iri = do_parse(800000)
                    ^^^^^^^^^^^^^^^^
  File "/home/yasin/miniconda3/lib/python3.12/site-packages/owlready2/driver.py", line 244, in do_parse
    queue.put(("error", e.args))
  File "/home/yasin/miniconda3/lib/python3.12/site-packages/owlready2/driver.py", line 53, in put
    elif command == "error":  raise OwlReadyOntologyParsingError(*args)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
owlready2.base.OwlReadyOntologyParsingError: ('error', ('RDF/XML parsing error in file ./data/ms.owl, line 24, column 75.',)) 
```

**Comment by mobiusklein** [comment]
Odd. I cannot reproduce that error:
```python
In [1]: import owlready2

In [2]: owlready2.VERSION
Out[2]: '0.47'

In [3]: onto = owlready2.get_ontology("./psi-ms.owl")

In [4]: onto.load()
Out[4]: get_ontology("http://purl.obolibrary.org/obo/ms.owl#")
```

**Comment by YasinEl** [comment]
Hmmm interesting. How about the following? I get the same error with the PSI one. http://aber-owl.net/media/ontologies/MS/189/ms.owl works.



```
import owlready2

# print version of owlready in use
print(owlready2.VERSION)  

print("Loading MS ontology...")
onto = owlready2.get_ontology('http://aber-owl.net/media/ontologies/MS/189/ms.owl').load()
print("Successfully loaded MS ontology")

print("Loading PSI-MS ontology...")
onto = owlready2.get_ontology('https://github.com/HUPO-PSI/psi-ms-CV/blob/fix/owl-compliant/psi-ms.owl').load()
print("Successfully loaded PSI-MS ontology")

```

**Comment by mobiusklein** [comment]
Well, the OWL file is 82,830+ lines of actual XML long, so... something is wrong.

If you are using a GitHub URL to access a large file, it's better to use the "raw" access route: https://raw.githubusercontent.com/HUPO-PSI/psi-ms-CV/refs/heads/fix/owl-compliant/psi-ms.owl

Using the regular URL gets you the human-friendly website wrapping the file's contents, with lots of HTML, CSS, JS, and whatnot between your program and the data you actually want.

**Comment by YasinEl** [comment]
Oh, I apologize, you are correct.

You solved the problem, thank you very much!

**Comment by mobiusklein** [comment]
Great. I'll initiate a PR to get a proper release with this change.
